### ISSUE TITLE
Query : Do you have any plans to get compatible with krikstone

### ISSUE THREAD

**Issue by Vishwasrao1** [Azure/meta-iotedge#84] opened 2022-06-15 07:07 UTC
As yocto is now having krikstone as LTS branch, do you plan to be compatible with the same?

**Comment by aurelihein** [comment] 2022-06-20 15:26
I am also very interested in the upgrade to support last [Yocto Kirkstone 4.0](https://docs.yoctoproject.org/dev/migration-guides/migration-4.0.html) !
It might go with [iot-identity-service compatible with Openssl 3.0](https://github.com/Azure/iot-identity-service/issues/413)

**Comment by Vishwasrao1** [comment] 2022-06-23 09:20
Looks it will need lot of changes to the core, I believe this will take time. However, it will be interesting to see the developments  @aurelihein . I keep this issue open for others to give input.

**Comment by rschwarz-sotec** [comment] 2022-12-06 07:11
Hi,

anyone already working with kirkstone? Or any plans of "official" support?

**Comment by rschwarz-sotec** [comment] 2023-01-12 06:02
Hi,

I tried to do the kirkstone update by myself, but I run into very early build issues. As I am no expert in Rust, I want to ask first if my plan is doable or if there any other ideas.

What I tried
- checking out meta-iotedge on dunfell release
- add all dependencies as documented on their kirkstone release
```$ git submodule status
 013b5eeb580bc13b156aaf77d0c1175f75b89671 meta-clang (remotes/origin/kirkstone)
+37015b5f43cbcd49aef673d9697df14ed3bb96ae meta-iotedge (heads/dunfell)
+458ab61befa4fb5c192cd970ed0db2225f0c5030 meta-rust (remotes/origin/fix-ci-6-g458ab61)
+c79262a30bd385f5dbb009ef8704a1a01644528e meta-security (heads/kirkstone)
+927537108bcf2b98859512ce3eae59a73439994d meta-virtualization (heads/kirkstone)
 2e79b199114b25d81bfaa029ccfb17676946d20d poky (yocto-4.0.5)
```
- add kirkstone to LAYERSERIES_COMPAT in meta-rust/conf/layer.conf
- add kirkstone to LAYERSERIES_COMPAT in meta-iotedge/conf/layer.conf
- run convertion scripts from poky/scripts/contrib against recipes in meta-iotedge
- changes in meta-iotedge:
<details><summary>CLICK ME</summary>
```
diff --git a/conf/layer.conf b/conf/layer.conf
index 02b0396..aa31239 100644
--- a/conf/layer.conf
+++ b/conf/layer.conf
@@ -9,6 +9,6 @@ BBFILE_COLLECTIONS += "meta-iotedge"
 BBFILE_PATTERN_meta-iotedge = "^${LAYERDIR}/"
 BBFILE_PRIORITY_meta-iotedge = "10"
 
-LAYERDEPENDS_meta-iotedge = "core rust-layer virtualization-layer"
-LAYERSERIES_COMPAT_meta-iotedge = "dunfell"
+LAYERDEPENDS_meta-iotedge = "core virtualization-layer"
+LAYERSERIES_COMPAT_meta-iotedge = "dunfell kirkstone"
 
diff --git a/conf/local.conf.sample b/conf/local.conf.sample
index c489f90..302be76 100644
--- a/conf/local.conf.sample
+++ b/conf/local.conf.sample
@@ -234,8 +234,8 @@ SSTATE_MIRRORS = "\
 # seen. The two lines below enable the SDL backend too. By default libsdl-native will
 # be built, if you want to use your host's libSDL instead of the minimal libsdl built
 # by libsdl-native then uncomment the ASSUME_PROVIDED line below.
-PACKAGECONFIG_append_pn-qemu-native = " sdl"
-PACKAGECONFIG_append_pn-nativesdk-qemu = " sdl"
+PACKAGECONFIG:append:pn-qemu-native = " sdl"
+PACKAGECONFIG:append:pn-nativesdk-qemu = " sdl"
 #ASSUME_PROVIDED += "libsdl-native"
 
 # CONF_VERSION is increased each time build/conf/ changes incompatibly and is used to
@@ -243,6 +243,6 @@ PACKAGECONFIG_append_pn-nativesdk-qemu = " sdl"
 # this doesn't mean anything to you.
 CONF_VERSION = "1"
 
-DISTRO_FEATURES_append = " systemd virtualization"
+DISTRO_FEATURES:append = " systemd virtualization"
 VIRTUAL-RUNTIME_init_manager = "systemd"
 VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
diff --git a/recipes-core/aziot-edged/aziot-edged.inc b/recipes-core/aziot-edged/aziot-edged.inc
index 26d7786..7844acc 100644
--- a/recipes-core/aziot-edged/aziot-edged.inc
+++ b/recipes-core/aziot-edged/aziot-edged.inc
@@ -1,10 +1,10 @@
 DEPENDS += "openssl virtual/docker iotedge aziotd systemd"
-RDEPENDS_${PN} += "docker iotedge aziotd aziot-keys systemd"
+RDEPENDS:${PN} += "docker iotedge aziotd aziot-keys systemd"
 
 inherit systemd
 
-SYSTEMD_AUTO_ENABLE_${PN} = "enable"
-SYSTEMD_SERVICE_${PN} = "aziot-edged.service"
+SYSTEMD_AUTO_ENABLE:${PN} = "enable"
+SYSTEMD_SERVICE:${PN} = "aziot-edged.service"
 
 
 SRC_URI += "file://aziot-edged.service \
@@ -42,12 +42,12 @@ do_install () {
 
 inherit useradd
 USERADD_PACKAGES = "${PN}"
-USERADD_PARAM_${PN} = "-r -g iotedge -c 'iotedge user' -G docker,systemd-journal,aziotcs,aziotks,aziottpm,aziotid -s /sbin/nologin -d ${localstatedir}/lib/aziot/edged iotedge; "
-USERADD_PARAM_${PN} += "-r -g iotedge -c 'edgeAgent user' -s /bin/sh -u 13622 edgeagentuser; "
-USERADD_PARAM_${PN} += "-r -g iotedge -c 'edgeHub user' -s /bin/sh -u 13623 edgehubuser; "
-GROUPADD_PARAM_${PN} = "-r iotedge"
+USERADD_PARAM:${PN} = "-r -g iotedge -c 'iotedge user' -G docker,systemd-journal,aziotcs,aziotks,aziottpm,aziotid -s /sbin/nologin -d ${localstatedir}/lib/aziot/edged iotedge; "
+USERADD_PARAM:${PN} += "-r -g iotedge -c 'edgeAgent user' -s /bin/sh -u 13622 edgeagentuser; "
+USERADD_PARAM:${PN} += "-r -g iotedge -c 'edgeHub user' -s /bin/sh -u 13623 edgehubuser; "
+GROUPADD_PARAM:${PN} = "-r iotedge"
 
-FILES_${PN} += " \
+FILES:${PN} += " \
     ${systemd_unitdir}/system/* \
     ${localstatedir}/lib/ \
     ${localstatedir}/log/ \
diff --git a/recipes-core/aziot-edged/aziot-edged_1.4.4.bb b/recipes-core/aziot-edged/aziot-edged_1.4.4.bb
index 6a9dbea..72dd485 100644
--- a/recipes-core/aziot-edged/aziot-edged_1.4.4.bb
+++ b/recipes-core/aziot-edged/aziot-edged_1.4.4.bb
@@ -234,82 +234,82 @@ SRC_URI += " \
 "
 
 SRCREV_FORMAT .= "_aziot-cert-client-async"
-SRCREV_aziot-cert-client-async = "release/1.4"
+SRCREV_aziot-cert-client-async = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-cert-client-async"
 SRCREV_FORMAT .= "_aziot-cert-common-http"
-SRCREV_aziot-cert-common-http = "release/1.4"
+SRCREV_aziot-cert-common-http = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-cert-common-http"
 SRCREV_FORMAT .= "_aziot-certd-config"
-SRCREV_aziot-certd-config = "release/1.4"
+SRCREV_aziot-certd-config = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-certd-config"
 SRCREV_FORMAT .= "_aziot-identity-client-async"
-SRCREV_aziot-identity-client-async = "release/1.4"
+SRCREV_aziot-identity-client-async = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-identity-client-async"
 SRCREV_FORMAT .= "_aziot-identity-common"
-SRCREV_aziot-identity-common = "release/1.4"
+SRCREV_aziot-identity-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-identity-common"
 SRCREV_FORMAT .= "_aziot-identity-common-http"
-SRCREV_aziot-identity-common-http = "release/1.4"
+SRCREV_aziot-identity-common-http = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-identity-common-http"
 SRCREV_FORMAT .= "_aziot-identityd-config"
-SRCREV_aziot-identityd-config = "release/1.4"
+SRCREV_aziot-identityd-config = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-identityd-config"
 SRCREV_FORMAT .= "_aziot-key-client"
-SRCREV_aziot-key-client = "release/1.4"
+SRCREV_aziot-key-client = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-key-client"
 SRCREV_FORMAT .= "_aziot-key-client-async"
-SRCREV_aziot-key-client-async = "release/1.4"
+SRCREV_aziot-key-client-async = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-key-client-async"
 SRCREV_FORMAT .= "_aziot-key-common"
-SRCREV_aziot-key-common = "release/1.4"
+SRCREV_aziot-key-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-key-common"
 SRCREV_FORMAT .= "_aziot-key-common-http"
-SRCREV_aziot-key-common-http = "release/1.4"
+SRCREV_aziot-key-common-http = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-key-common-http"
 SRCREV_FORMAT .= "_aziot-key-openssl-engine"
-SRCREV_aziot-key-openssl-engine = "release/1.4"
+SRCREV_aziot-key-openssl-engine = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-key-openssl-engine"
 SRCREV_FORMAT .= "_aziot-keyd-config"
-SRCREV_aziot-keyd-config = "release/1.4"
+SRCREV_aziot-keyd-config = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-keyd-config"
 SRCREV_FORMAT .= "_aziot-keys-common"
-SRCREV_aziot-keys-common = "release/1.4"
+SRCREV_aziot-keys-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-keys-common"
 SRCREV_FORMAT .= "_aziot-tpmd-config"
-SRCREV_aziot-tpmd-config = "release/1.4"
+SRCREV_aziot-tpmd-config = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-tpmd-config"
 SRCREV_FORMAT .= "_aziotctl-common"
-SRCREV_aziotctl-common = "release/1.4"
+SRCREV_aziotctl-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziotctl-common"
 SRCREV_FORMAT .= "_cert-renewal"
-SRCREV_cert-renewal = "release/1.4"
+SRCREV_cert-renewal = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/cert-renewal"
 SRCREV_FORMAT .= "_config-common"
-SRCREV_config-common = "release/1.4"
+SRCREV_config-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/config-common"
 SRCREV_FORMAT .= "_http-common"
-SRCREV_http-common = "release/1.4"
+SRCREV_http-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/http-common"
 SRCREV_FORMAT .= "_logger"
-SRCREV_logger = "release/1.4"
+SRCREV_logger = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/logger"
 SRCREV_FORMAT .= "_openssl-build"
-SRCREV_openssl-build = "release/1.4"
+SRCREV_openssl-build = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/openssl-build"
 SRCREV_FORMAT .= "_openssl-sys2"
-SRCREV_openssl-sys2 = "release/1.4"
+SRCREV_openssl-sys2 = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/openssl-sys2"
 SRCREV_FORMAT .= "_openssl2"
-SRCREV_openssl2 = "release/1.4"
+SRCREV_openssl2 = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/openssl2"
 SRCREV_FORMAT .= "_pkcs11"
-SRCREV_pkcs11 = "release/1.4"
+SRCREV_pkcs11 = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/pkcs11"
 SRCREV_FORMAT .= "_pkcs11-sys"
-SRCREV_pkcs11-sys = "release/1.4"
+SRCREV_pkcs11-sys = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/pkcs11-sys"
 SRCREV_FORMAT .= "_test-common"
-SRCREV_test-common = "release/1.4"
+SRCREV_test-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/test-common"
 
 LIC_FILES_CHKSUM=" \
diff --git a/recipes-core/aziot-keys/aziot-keys.inc b/recipes-core/aziot-keys/aziot-keys.inc
index 63fc6a6..07d0318 100644
--- a/recipes-core/aziot-keys/aziot-keys.inc
+++ b/recipes-core/aziot-keys/aziot-keys.inc
@@ -1,4 +1,4 @@
 DEPENDS += "openssl virtual/docker "
-RDEPENDS_${PN} += "docker "
+RDEPENDS:${PN} += "docker "
 
 SRC_URI +="file://0001-Change-panic-strategy-to-unwind.patch"
diff --git a/recipes-core/aziotctl/aziotctl.inc b/recipes-core/aziotctl/aziotctl.inc
index f560515..47cab16 100644
--- a/recipes-core/aziotctl/aziotctl.inc
+++ b/recipes-core/aziotctl/aziotctl.inc
@@ -1,5 +1,5 @@
 DEPENDS += "openssl virtual/docker"
-RDEPENDS_${PN} += "docker"
+RDEPENDS:${PN} += "docker"
 
 export OPENSSL_DIR = "${STAGING_EXECPREFIXDIR}"
 
diff --git a/recipes-core/aziotd/aziotd.inc b/recipes-core/aziotd/aziotd.inc
index 4060e71..fc067b9 100644
--- a/recipes-core/aziotd/aziotd.inc
+++ b/recipes-core/aziotd/aziotd.inc
@@ -1,14 +1,14 @@
 DEPENDS += "openssl virtual/docker aziotctl aziot-keys tpm2-tss clang-native libtss2"
-RDEPENDS_${PN} += "docker libtss2 libtss2-mu libtss2-tcti-device aziot-keys"
+RDEPENDS:${PN} += "docker libtss2 libtss2-mu libtss2-tcti-device aziot-keys"
 TOOLCHAIN = "clang"
 
 inherit systemd 
 
-SYSTEMD_AUTO_ENABLE_${PN} = "enable"
-SYSTEMD_SERVICE_${PN} = "aziot-certd.service "
-SYSTEMD_SERVICE_${PN} += "aziot-identityd.service "
-SYSTEMD_SERVICE_${PN} += "aziot-keyd.service "
-SYSTEMD_SERVICE_${PN} += "aziot-tpmd.service "
+SYSTEMD_AUTO_ENABLE:${PN} = "enable"
+SYSTEMD_SERVICE:${PN} = "aziot-certd.service "
+SYSTEMD_SERVICE:${PN} += "aziot-identityd.service "
+SYSTEMD_SERVICE:${PN} += "aziot-keyd.service "
+SYSTEMD_SERVICE:${PN} += "aziot-tpmd.service "
 
 SRC_URI += "file://aziot-certd.service \
             file://aziot-identityd.service \
@@ -68,17 +68,17 @@ do_install () {
 
 inherit useradd
 USERADD_PACKAGES = "${PN}"
-USERADD_PARAM_${PN} = "-r -g aziotcs -c 'aziot-certd user' -G aziotks -s /sbin/nologin -d ${localstatedir}/lib/aziot/certd aziotcs; "
-USERADD_PARAM_${PN} += "-r -g aziotks -c 'aziot-keyd user' -s /sbin/nologin -d ${localstatedir}/lib/aziot/keyd aziotks; "
-USERADD_PARAM_${PN} += "-r -g aziotid -c 'aziot-identityd user' -G aziotcs,aziotks,aziottpm -s /sbin/nologin -d ${localstatedir}/lib/aziot/identityd aziotid; "
-USERADD_PARAM_${PN} += "-r -g aziottpm -c 'aziot-tpmd user' -s /sbin/nologin -d ${localstatedir}/lib/aziot/tpmd aziottpm; "
+USERADD_PARAM:${PN} = "-r -g aziotcs -c 'aziot-certd user' -G aziotks -s /sbin/nologin -d ${localstatedir}/lib/aziot/certd aziotcs; "
+USERADD_PARAM:${PN} += "-r -g aziotks -c 'aziot-keyd user' -s /sbin/nologin -d ${localstatedir}/lib/aziot/keyd aziotks; "
+USERADD_PARAM:${PN} += "-r -g aziotid -c 'aziot-identityd user' -G aziotcs,aziotks,aziottpm -s /sbin/nologin -d ${localstatedir}/lib/aziot/identityd aziotid; "
+USERADD_PARAM:${PN} += "-r -g aziottpm -c 'aziot-tpmd user' -s /sbin/nologin -d ${localstatedir}/lib/aziot/tpmd aziottpm; "
 
-GROUPADD_PARAM_${PN} = "-r aziotcs; "
-GROUPADD_PARAM_${PN} += "-r aziotks; "
-GROUPADD_PARAM_${PN} += "-r aziotid; "
-GROUPADD_PARAM_${PN} += "-r aziottpm; "
+GROUPADD_PARAM:${PN} = "-r aziotcs; "
+GROUPADD_PARAM:${PN} += "-r aziotks; "
+GROUPADD_PARAM:${PN} += "-r aziotid; "
+GROUPADD_PARAM:${PN} += "-r aziottpm; "
 
-FILES_${PN} += " \
+FILES:${PN} += " \
     ${systemd_unitdir}/system/* \
     ${bindir}/aziot-* \
     ${localstatedir}/lib/ \
diff --git a/recipes-core/aziotd/aziotd_%.bbappend b/recipes-core/aziotd/aziotd_%.bbappend
index 5230d81..7227ffa 100644
--- a/recipes-core/aziotd/aziotd_%.bbappend
+++ b/recipes-core/aziotd/aziotd_%.bbappend
@@ -6,6 +6,6 @@ BINDGEN_EXTRA_CLANG_ARGS = "${@bb.utils.contains('target', 'arm', \
 export BINDGEN_EXTRA_CLANG_ARGS
 
 # Copy keys.generated.rs
-do_compile_prepend () {
+do_compile:prepend () {
     install -m 644 ${WORKDIR}/keys.generated.rs ${WORKDIR}/git/key/aziot-keyd/src/keys.generated.rs
 }
diff --git a/recipes-core/iotedge/iotedge_1.4.4.bb b/recipes-core/iotedge/iotedge_1.4.4.bb
index bf6a44b..6a0a0e8 100644
--- a/recipes-core/iotedge/iotedge_1.4.4.bb
+++ b/recipes-core/iotedge/iotedge_1.4.4.bb
@@ -234,82 +234,82 @@ SRC_URI += " \
 "
 
 SRCREV_FORMAT .= "_aziot-cert-client-async"
-SRCREV_aziot-cert-client-async = "release/1.4"
+SRCREV_aziot-cert-client-async = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-cert-client-async"
 SRCREV_FORMAT .= "_aziot-cert-common-http"
-SRCREV_aziot-cert-common-http = "release/1.4"
+SRCREV_aziot-cert-common-http = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-cert-common-http"
 SRCREV_FORMAT .= "_aziot-certd-config"
-SRCREV_aziot-certd-config = "release/1.4"
+SRCREV_aziot-certd-config = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-certd-config"
 SRCREV_FORMAT .= "_aziot-identity-client-async"
-SRCREV_aziot-identity-client-async = "release/1.4"
+SRCREV_aziot-identity-client-async = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-identity-client-async"
 SRCREV_FORMAT .= "_aziot-identity-common"
-SRCREV_aziot-identity-common = "release/1.4"
+SRCREV_aziot-identity-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-identity-common"
 SRCREV_FORMAT .= "_aziot-identity-common-http"
-SRCREV_aziot-identity-common-http = "release/1.4"
+SRCREV_aziot-identity-common-http = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-identity-common-http"
 SRCREV_FORMAT .= "_aziot-identityd-config"
-SRCREV_aziot-identityd-config = "release/1.4"
+SRCREV_aziot-identityd-config = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-identityd-config"
 SRCREV_FORMAT .= "_aziot-key-client"
-SRCREV_aziot-key-client = "release/1.4"
+SRCREV_aziot-key-client = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-key-client"
 SRCREV_FORMAT .= "_aziot-key-client-async"
-SRCREV_aziot-key-client-async = "release/1.4"
+SRCREV_aziot-key-client-async = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-key-client-async"
 SRCREV_FORMAT .= "_aziot-key-common"
-SRCREV_aziot-key-common = "release/1.4"
+SRCREV_aziot-key-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-key-common"
 SRCREV_FORMAT .= "_aziot-key-common-http"
-SRCREV_aziot-key-common-http = "release/1.4"
+SRCREV_aziot-key-common-http = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-key-common-http"
 SRCREV_FORMAT .= "_aziot-key-openssl-engine"
-SRCREV_aziot-key-openssl-engine = "release/1.4"
+SRCREV_aziot-key-openssl-engine = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-key-openssl-engine"
 SRCREV_FORMAT .= "_aziot-keyd-config"
-SRCREV_aziot-keyd-config = "release/1.4"
+SRCREV_aziot-keyd-config = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-keyd-config"
 SRCREV_FORMAT .= "_aziot-keys-common"
-SRCREV_aziot-keys-common = "release/1.4"
+SRCREV_aziot-keys-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-keys-common"
 SRCREV_FORMAT .= "_aziot-tpmd-config"
-SRCREV_aziot-tpmd-config = "release/1.4"
+SRCREV_aziot-tpmd-config = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziot-tpmd-config"
 SRCREV_FORMAT .= "_aziotctl-common"
-SRCREV_aziotctl-common = "release/1.4"
+SRCREV_aziotctl-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/aziotctl-common"
 SRCREV_FORMAT .= "_cert-renewal"
-SRCREV_cert-renewal = "release/1.4"
+SRCREV_cert-renewal = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/cert-renewal"
 SRCREV_FORMAT .= "_config-common"
-SRCREV_config-common = "release/1.4"
+SRCREV_config-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/config-common"
 SRCREV_FORMAT .= "_http-common"
-SRCREV_http-common = "release/1.4"
+SRCREV_http-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/http-common"
 SRCREV_FORMAT .= "_logger"
-SRCREV_logger = "release/1.4"
+SRCREV_logger = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/logger"
 SRCREV_FORMAT .= "_openssl-build"
-SRCREV_openssl-build = "release/1.4"
+SRCREV_openssl-build = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/openssl-build"
 SRCREV_FORMAT .= "_openssl-sys2"
-SRCREV_openssl-sys2 = "release/1.4"
+SRCREV_openssl-sys2 = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/openssl-sys2"
 SRCREV_FORMAT .= "_openssl2"
-SRCREV_openssl2 = "release/1.4"
+SRCREV_openssl2 = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/openssl2"
 SRCREV_FORMAT .= "_pkcs11"
-SRCREV_pkcs11 = "release/1.4"
+SRCREV_pkcs11 = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/pkcs11"
 SRCREV_FORMAT .= "_pkcs11-sys"
-SRCREV_pkcs11-sys = "release/1.4"
+SRCREV_pkcs11-sys = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/pkcs11-sys"
 SRCREV_FORMAT .= "_test-common"
-SRCREV_test-common = "release/1.4"
+SRCREV_test-common = "b3b290122e2e518f7318ca5b2ad7f41194fd232d"
 EXTRA_OECARGO_PATHS += "${WORKDIR}/test-common"
 
 LIC_FILES_CHKSUM=" \

```
</details>

Build result is:
```
<details><summary>CLICK ME</summary>
<p>

#### We can hide anything, even code!

```
ERROR: aziotctl-1.4.1.AUTOINC+f349b64d3b-r0 do_compile: ExecutionError('/workdir/odroid-c4/build/tmp/work/cortexa55-poky-linux/aziotctl/1.4.1.AUTOINC+f349b64d3b-r0/temp/run.do_compile.128', 101, None, None)
ERROR: Logfile of failure stored in: /workdir/odroid-c4/build/tmp/work/cortexa55-poky-linux/aziotctl/1.4.1.AUTOINC+f349b64d3b-r0/temp/log.do_compile.128
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: cargo = /workdir/odroid-c4/build/tmp/work/cortexa55-poky-linux/aziotctl/1.4.1.AUTOINC+f349b64d3b-r0/recipe-sysroot-native/usr/bin/cargo
| NOTE: rustc =
| NOTE: cargo build -v --target aarch64-poky-linux --release --manifest-path=/workdir/odroid-c4/build/tmp/work/cortexa55-poky-linux/aziotctl/1.4.1.AUTOINC+f349b64d3b-r0/git/aziotctl/Cargo.toml
| error: failed to get `anyhow` as a dependency of package `aziotctl v1.4.1 (/workdir/odroid-c4/build/tmp/work/cortexa55-poky-linux/aziotctl/1.4.1.AUTOINC+f349b64d3b-r0/git/aziotctl)`
| 
| Caused by:
|   failed to load source for dependency `anyhow`
| 
| Caused by:
|   Unable to update registry `crates-io`
| 
| Caused by:
|   failed to update replaced source registry `crates-io`
| 
| Caused by:
|   failed to parse manifest at `/workdir/odroid-c4/build/tmp/work/cortexa55-poky-linux/aziotctl/1.4.1.AUTOINC+f349b64d3b-r0/cargo_home/bitbake/serde_with-2.0.0/Cargo.toml`
| 
| Caused by:
|   namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
| WARNING: /workdir/odroid-c4/build/tmp/work/cortexa55-poky-linux/aziotctl/1.4.1.AUTOINC+f349b64d3b-r0/temp/run.do_compile.128:176 exit 101 from '"cargo" build -v --target aarch64-poky-linux --release --manifest-path=/workdir/odroid-c4/build/tmp/work/cortexa55-poky-linux/aziotctl/1.4.1.AUTOINC+f349b64d3b-r0/git/aziotctl/Cargo.toml "$@"'
| WARNING: Backtrace (BB generated script):
|       #1: oe_cargo_build, /workdir/odroid-c4/build/tmp/work/cortexa55-poky-linux/aziotctl/1.4.1.AUTOINC+f349b64d3b-r0/temp/run.do_compile.128, line 176
|       #2: cargo_do_compile, /workdir/odroid-c4/build/tmp/work/cortexa55-poky-linux/aziotctl/1.4.1.AUTOINC+f349b64d3b-r0/temp/run.do_compile.128, line 166
|       #3: do_compile, /workdir/odroid-c4/build/tmp/work/cortexa55-poky-linux/aziotctl/1.4.1.AUTOINC+f349b64d3b-r0/temp/run.do_compile.128, line 160
|       #4: main, /workdir/odroid-c4/build/tmp/work/cortexa55-poky-linux/aziotctl/1.4.1.AUTOINC+f349b64d3b-r0/temp/run.do_compile.128, line 208
ERROR: Task (/workdir/meta-iotedge/recipes-core/aziotctl/aziotctl_1.4.1.bb:do_compile) failed with exit code '1'
```

</p>
</details>
```

My questions:
- Is this the right way of doing the migration?
- I read something about rust support in yocto [link](https://github.com/meta-rust/meta-rust/issues/380). Is meta-rust still needed on kirkstone?
- Is anybody else working on this? Are there any plans when kirkstone support will be releases?

I would be happy if I can support development for kirkstone! It would be great to get some advice how to get started.

Cheers
Ruben

**Comment by MZDN** [comment] 2023-01-15 22:53
Is there any update on this ?

**Comment by rschwarz-sotec** [comment] 2023-01-16 07:54
Not from my side, I'm still waiting for any response.

**Comment by micahl** [comment] 2023-01-18 23:50
@timesys-nathan contributed a PR (https://github.com/Azure/meta-iotedge/pull/107) that we will review (thanks!).  Related to Kirkstone (and other distros like the latest Ubuntu or RHEL) is working with openssl 3.0 and we're investigating why one of our e2e tests fails.

**Comment by theobarkerh** [comment] 2023-02-15 19:13
We definitely need Kirkstone support ASAP. 
Longer term: does MS plan to support Yocto as a Tier 1 environment? Seems that it would be wise considering how many IoT devices use it.

**Comment by micahl** [comment] 2023-03-03 01:08
Closing as now complete (see https://github.com/Azure/meta-iotedge/commit/63785dfcf446a3f48ca9a7a26ca121109746b64e).  Thanks @timesys-nathan for the contribution and @theobarkerh and @rschwarz-sotec for help in validating!

**Closed by micahl** 2023-03-03 01:08 UTC
